### ISSUE TITLE
Script not working. Log.txt shows Import error

### ISSUE THREAD

**Issue by Doomski99** [MrMatch246/KeyLab_Essential_mk3_TGE#18]
Hello,

I'm having troubles with my Keylab essential Mk3 88 where the display is not integrated with Ableton nor when it launches analog lab from within. I followed the instructions and your script doesn't seem to work. Checking the logs, I found this error:

> 2024-07-08T20:52:56.481347: info: Directories: Core Library Slice dir: [C:\ProgramData\Ableton\Live 12 Suite\Resources\Core Library] 
> 2024-07-08T20:52:56.489196: error: RemoteScriptError: Traceback (most recent call last):
> 
> 2024-07-08T20:52:56.489207: error: RemoteScriptError:   File "<string>", line 1, in <module>
> 
> 2024-07-08T20:52:56.489287: error: RemoteScriptError:   File "C:\Users\...\Documents\Ableton\User Library\Remote Scripts\KeyLab_Essential_mk3_TGE\__init__.py", line 23, in <module>
> 
> 2024-07-08T20:52:56.489369: error: RemoteScriptError:     
> 2024-07-08T20:52:56.489378: error: RemoteScriptError: from .devices import DeviceBankToggleComponent, DeviceControlsComponent
> 2024-07-08T20:52:56.489385: error: RemoteScriptError: 
> 
> 2024-07-08T20:52:56.489392: error: RemoteScriptError:   File "C:\Users\...\Documents\Ableton\User Library\Remote Scripts\KeyLab_Essential_mk3_TGE\devices.py", line 8, in <module>
> 
> 2024-07-08T20:52:56.489454: error: RemoteScriptError:     
> 2024-07-08T20:52:56.489463: error: RemoteScriptError: from ableton.v3.control_surface.components import DeviceNavigationComponent
> 2024-07-08T20:52:56.489469: error: RemoteScriptError: 
> 
> 2024-07-08T20:52:56.489476: error: RemoteScriptError: ImportError
> 2024-07-08T20:52:56.489482: error: RemoteScriptError: : 
> 2024-07-08T20:52:56.489490: error: RemoteScriptError: cannot import name 'DeviceNavigationComponent' from 'ableton.v3.control_surface.components' (C:\ProgramData\Ableton\Live 12 Suite\Resources\MIDI Remote Scripts\ableton\v3\control_surface\components\__init__.pyc)
> 2024-07-08T20:52:56.489496: error: RemoteScriptError:

**Comment by MrMatch246** [comment]
I think ive seen that before, is this the newest version on the master branch or the newest release you are using? Which version of ableton are you using?
(ill look into it later today)

**Comment by Doomski99** [comment]
@MrMatch246 I'm using the latest release with Ableton 12.0

**Comment by MrMatch246** [comment]
12.0 or 12.0.5? They changed some stuff going to 12.0.5 if you use an earlier version, you should try the first release and if that works i can try an see if i can maybe make it work for both

**Comment by Doomski99** [comment]
I'll try to update to 12.0.5 tomorrow and see if it changes something

**Comment by MrMatch246** [comment]
Ah yeah in that case just use a previous release of mine or the commit before the 12
0.5 update

**Comment by MrMatch246** [comment]
Any success?

**Comment by Doomski99** [comment]
> Any success?

It worked! That's crazy. I downloaded the previous commit. Thanks man :)

**Comment by MrMatch246** [comment]
So if you ever update ableton, you will need to use the latest release.
